
Anglais_voc1_famille = {
    'tante': 'aunt',
    'trouver (qqch) ennuyeux (v)': 'bored (with sth)',
    'frère': 'brother',
    'cousin(e)': 'cousin',
    'papa': 'dad',
    'fille': 'daughter',
    'petite-fille': 'granddaughter',
    'grand-père': 'grandfather',
    'grand-mère': 'grandmother',
    'grand-parent': 'grandparent',
    'petit-fils': 'grandson',
    'mari/époux': 'husband',
    'maman': 'mum',
    'neveu': 'nephew',
    'nièce': 'niece',
    'parent': 'parent',
    'sœur': 'sister',
    'fils': 'son',
    'oncle': 'uncle',
    'femme/épouse': 'wife',
    '(lire un) livre': '(read a) book',
    'automne': 'autumn',
    'printemps': 'spring',
    'été': 'summer',
    'hiver': 'winter'
}

Anglais_voc2_school = {
    '(vérifier votre) réponse': '(check your) answer',
    '(jouer au) football': '(play) football',
    "s'habiller": 'get dressed',
    'rentrer (chez soi)': 'get home',
    'se lever': 'get up',
    '(aller) se coucher': 'go to bed',
    'prendre une douche': 'have a shower',
    'prendre son/le petit-déjeuner': 'have breakfast',
    'dîner': 'have dinner',
    'déjeuner': 'have lunch',
    '(faire ses) devoirs': '(do) homework',
    '(utiliser) internet': '(use the) internet',
    'rencontrer (des amis)': 'meet (friends)',
    '(travailler en) binômes': '(work in) pairs',
    '(discuter au) téléphone': '(chat on the) phone',
    'commencer les cours': 'start school',
    '(lire un) texte': '(read a) text',
    'regarder la télé': 'watch TV',
    'marcher/ (aller) à l\'école à pied': 'walk',
    'art': 'art',
    'éducation civique': 'citizenship',
    'arts dramatiques': 'drama',
    'technologie': 'DT',
    'anglais': 'English',
    'géographie': 'geography',
    'histoire': 'history',
    'informatique': 'ICT',
    'mathématiques (maths)': 'maths',
    'langues vivantes': 'modern languages',
    'éducation physique et sportive (EPS)': 'PE',
    'éducation religieuse': 'RE',
    'SVT (sciences de la vie et de la Terre)': 'science',
    'professeur/enseignant': 'teacher',
    '(à/en) vélo': '(by) bike',
    '(en) bus': '(by) bus',
    '(en) voiture': '(by) car',
    '(écouter un) dialogue': '(listen to a) dialogue',
    'à pied': 'on foot',
    '(en) avion': '(by) plane',
    'élève/étudiant': 'student',
    '(en) train': '(by) train',
    'musique': 'music',
    'cartable/sac (de cours)': 'school bag',
    'poubelle': 'bin',
    'tableau noir': 'blackboard',
    '(regarder le) tableau': '(look at the) board',
    'calculatrice': 'calculator',
    'chaise': 'chair',
    'horloge/réveil': 'clock',
    'bureau': 'desk',
    'agenda': 'diary',
    'dictionnaire': 'dictionary',
    'porte': 'door',
    '(faire un) exercice': '(do an) exercise',
    'cahier': 'exercise book',
    'chemise/pochette': 'folder',
    'colle': 'glue',
    'tableau blanc interactif': 'interactive whiteboard',
    'carte': 'map',
    'stylo': 'pen',
    'crayon': 'pencil',
    'trousse': 'pencil case',
    'taille-crayon': 'pencil sharpener',
    'Poster/affiche': 'poster',
    'gomme': 'rubber',
    'règle': 'ruler',
    'ciseaux': 'scissors',
    '(écrire une) phrase': '(write a) sentence',
    'feuille (de papier)': 'sheet of paper',
    'manuel': 'textbook',
    'fenêtre': 'window',
    '(apprendre du) vocabulaire': '(learn) vocabulary',
    '(lire le) mot': '(read the) word',
    'poser une question': 'ask a question',
    'faire des recherches': 'do some research',
    'créer une carte heuristique': 'make a mind map',
    'réviser pour un contrôle': 'revise for a test',
    '(étudier pour un) contrôle': '(study for a) test',
    'écrire une rédaction/dissertation': 'write an essay'
}

Anglais_voc3_loisire = {
    'jouer un rôle (v)': 'acting',
    '(jouer à un) jeu vidéo': '(play a) computer game',
    'cuisine': 'cooking',
    'danse': 'dancing',
    'différent': 'different',
    'difficile': 'difficult',
    'dessin': 'drawing',
    '(jouer de la) batterie': '(play the) drums',
    'aimer': 'enjoy',
    'bon': 'good',
    'intéressé (par quelque chose/quelqu\'un)': 'interested (in sb / sth)',
    'adorer/être fan de (quelque chose)': '(be) into (sth)',
    'aimer': 'like',
    'adorer': 'love',
    'nouveau': 'new',
    'peinture': 'painting',
    'escalade': 'rock climbing',
    'même': 'same',
    'chant': 'singing',
    'skateboard': 'skateboarding',
    'natation': 'swimming',
    '(jouer au) tennis': '(play) tennis',
    'basket': 'basketball',
    'piano': 'piano',
    'rugby': 'rugby',
    'mauvais': 'bad',
    'grand/gros': 'big',
    'violoncelle': 'cello',
    'clarinette': 'clarinet',
    'facile': 'easy',
    'flûte': 'flute',
    'guitare': 'guitar',
    'karaté': 'karate',
    'clavier': 'keyboards',
    'bruyant': 'noisy',
    'silencieux': 'quiet',
    'saxophone': 'saxophone',
    'petit': 'small',
    'trompette': 'trumpet',
    'inhabituel': 'unusual',
    'habituel': 'usual',
    'violon': 'violin',
    'rapide': 'quick',
    'ancien': 'old',
    'aérobic': 'aerobics',
    'tir à l\'arc': 'archery',
    'athlétisme': 'athletics',
    'badminton': 'badminton',
    'canoë': 'canoeing',
    'cricket': 'cricket',
    'gymnastique': 'gymnastics',
    'hockey': 'hockey',
    'course à pied': 'running',
    'voile': 'sailing',
    'ski': 'skiing',
    'volley': 'volleyball',
    'bain': 'bath',
    'salle de bain': 'bathroom',
    'lit': 'bed',
    'chambre': 'bedroom',
    'plafond': 'ceiling',
    'commode': 'chest of drawers',
    'ville': 'city',
    'cuisinière': 'cooker',
    'placard': 'cupboard',
    'sol': 'floor',
    'réfrigérateur': 'fridge',
    'jardin': 'garden',
    'entrée': 'hall',
    'cuisine': 'kitchen',
    'salon': 'living room',
    'ensuite': 'next',
    'toit': 'roof',
    'tapis': 'rug',
    'douche': 'shower',
    'canapé': 'sofa',
    'table': 'table',
    'ensuite': 'then',
    'toilettes': 'toilet',
    'town': 'town',
    'mur': 'wall',
    'fenêtre': 'window',
    'café': 'café',
    'bibliothèque': 'library',
    'musée': 'museum',
    'parc': 'park',
    'centre commercial': 'shopping centre',
    'stade': 'stadium',
    'université': 'university',
    'arrêt de bus': 'bus stop',
    'cinéma': 'cinema',
    'centre-ville': 'city centre',
    'campagne': 'countryside',
    'hôpital': 'hospital',
    'centre sportif/de loisirs': 'leisure centre',
    'écouter attentivement': 'listen carefully',
    'banlieue': 'suburb',
    'théâtre': 'theatre',
    'gare': 'train station',
    'village': 'village',
    'ensuite': 'after that',
    'enfin': 'finally',
    'salle à manger': 'dining room',
    'étagère': 'shelf',
    'évier': 'sink',
    'fauteuil': 'armchair',
    'banque': 'bank',
    'table de nuit': 'bedside table',
    'bidet': 'bidet',
    'moquette': 'carpet',
    'rideaux': 'curtains',
    'coussin': 'cushion',
    'lave-vaisselle': 'dishwasher',
    'cheminée': 'fireplace',
    'congélateur': 'freezer',
    'porte d\'entrée': 'front door',
    'lampe': 'lamp',
    'miroir': 'mirror',
    'poste de police/gendarmerie': 'police station',
    'restaurant': 'restaurant',
    'volets': 'shutters',
    'escaliers': 'stairs',
    'armoire': 'wardrobe',
    'lavabo': 'washbasin',
    'machine à laver': 'washing machine',
    'demander l\'avis des autres': 'ask for other people’s opinions',
    'être clair': 'be clear',
    'être gentil': 'be kind',
    'd\'abord': 'first',
    'justifier son avis': 'give reasons for your opinions'
}

Anglais_voc4_natur = {
    'ours': 'bear',
    'mordre/piquer': 'bite',
    'cactus': 'cactus',
    'nuage': 'cloud',
    'froid': 'cold',
    'désert': 'desert',
    'creuser': 'dig',
    'fleur': 'flower',
    'suivre': 'follow',
    'forêt': 'forest',
    'renard': 'fox',
    'girafe': 'giraffe',
    'herbe': 'grass',
    'prairie': 'grassland',
    'chaud': 'hot',
    'chasser': 'hunt',
    'glace': 'ice',
    'chercher': 'look for',
    '(au) milieu': '(in the) middle',
    'montagne': 'mountain',
    'plante': 'plant',
    's\'enfuir': 'run away',
    'sable': 'sand',
    'neige': 'snow',
    'arbre': 'tree',
    'chat': 'cat',
    'chien': 'dog',
    'tigre': 'tiger',
    'nuageux': 'cloudy',
    'frais': 'cool',
    'pluvieux': 'rainy',
    'enneigé': 'snowy',
    'orageux': 'stormy',
    'ensoleillé': 'sunny',
    'surf': 'surfing',
    'chaud': 'warm',
    'venteux': 'windy',
    'escalade de bloc': 'bouldering',
    'saut à l\'élastique': 'bungee jumping',
    'spéléologie': 'caving',
    'centre': 'centre',
    'plongée': 'diving',
    'cheval': 'horse',
    'équitation': 'horse riding',
    'VTT': 'mountain biking',
    'snowboard': 'snowboarding',
    'zorbing (descente en bulle)': 'zorbing',
    'arrière-plan': 'background',
    '(en) bas': '(at the) bottom',
    'premier plan': 'foreground',
    '(en) haut': '(at the) top',
    'porter': 'carry',
    'perruche': 'budgie',
    'papillon': 'butterfly',
    'poulet': 'chicken',
    'vache': 'cow',
    'aigle': 'eagle',
    'éléphant': 'elephant',
    'poisson': 'fish',
    'cochon d\'inde': 'guinea pig',
    'hamster': 'hamster',
    'lézard': 'lizard',
    'singe': 'monkey',
    'souris': 'mouse',
    'perroquet': 'parrot',
    'cochon': 'pig',
    'lapin': 'rabbit',
    'mouton': 'sheep',
    'serpent': 'snake',
    'araignée': 'spider',
    'tortue terrestre': 'tortoise',
    'baleine': 'whale',
    'loup': 'wolf'
}

Anglais_voc5_nourriture = {
    'pomme': 'apple',
    'pain': 'bread',
    'carotte': 'carrot',
    'fromage': 'cheese',
    'chocolat': 'chocolate',
    'gâteau au chocolat': 'chocolate cake',
    'café': 'coffee',
    'concombre': 'cucumber',
    'salade de fruits': 'fruit salad',
    'sandwich au jambon': 'ham sandwich',
    'laitue': 'lettuce',
    'champignon': 'mushroom',
    'fruit à coque': 'nut',
    'orange': 'orange',
    'jus d\'orange': 'orange juice',
    'sucre': 'sugar',
    'tomate': 'tomato',
    'délicieux': 'delicious',
    '(un) kilo (de pommes)': '(a) kilo (of apples)',
    'pomme de terre': 'potato',
    'fraise': 'strawberry',
    'bol': 'bowl',
    'tasse': 'cup',
    'fourchette': 'fork',
    'verre': 'glass',
    'glace': 'ice cream',
    'pichet': 'jug',
    'couteau': 'knife',
    'mug': 'mug',
    'assiette': 'plate',
    'cuillère': 'spoon',
    'yaourt': 'yoghurt (also yogurt)',
    'ennuyeux': 'boring',
    'chips': 'crisps',
    'dégoûtant/répugnant': 'disgusting',
    'passionnant': 'exciting',
    'intéressant': 'interesting',
    'joli/agréable': 'lovely',
    'pizza aux champignons': 'mushroom pizza',
    'pâtes': 'pasta',
    'riz': 'rice',
    'saumon': 'salmon',
    'sel': 'salt',
    'effrayant': 'scary',
    'étrange/bizarre': 'strange',
    'bonbons': 'sweets',
    'sauce tomate': 'tomato sauce',
    '(une) bouteille (d\'eau)': '(a) bottle (of water)',
    '(une) canette (de coca)': '(a) can (of cola)',
    '(une) brique (de jus de fruit)': '(a) carton (of juice)',
    'crème': 'cream',
    'raisin': 'grape',
    '(un) bocal (de confiture)': '(a) jar (of jam)',
    'ketchup': 'ketchup',
    '(un) litre (d\'huile)': '(a) litre (of oil)',
    '(une) miche (de pain)': '(a) loaf (of bread)',
    'huile d\'olive': 'olive oil',
    'oignon': 'onion',
    '(un) paquet (de bonbons)': '(a) packet (of sweets)',
    'pêche': 'peach',
    'petits pois': 'peas',
    'poivron': 'pepper',
    '(une) part (de pizza)': '(a) slice (of pizza)',
    'steak': 'steak',
    '(une) boîte de conserve (de pêches)': '(a) tin (of peaches)',
    'vérifier vos paramètres de confidentialité': 'check your privacy settings',
    'choisir un mot de passe fort': 'choose a strong password',
    'cliquer sur un lien': 'click on a link',
    'télécharger un fichier': 'download a file',
    'installer une mise à jour de sécurité': 'install a security update',
    'publier une photo': 'post a photo'
}

Anglais_voc6_vetement = {
    'He wore jeans and a baggy T-shirt.': 'large/ample',
    'I need a new pair of boots for the winter.': 'bottes',
    'I’ve got a brand new computer!': 'flambant neuf/tout nouveau',
    'He always wore a baseball cap.': 'casquette',
    'Where’s my cardigan? It’s getting cold in here.': 'gilet',
    'That restaurant is very good and quite cheap.': 'pas cher/bon marché',
    'Put your coat on – it’s cold today.': 'manteau',
    'Syed only wears clothes with a designer label.': 'de marque',
    'I bought a new dress for the wedding.': 'robe',
    'She always wears expensive clothes.': 'cher',
    'She was wearing a fashionable black hat.': 'à la mode/tendance',
    'These jeans fit very well.': 'aller bien',
    'She’s wearing a hat.': 'chapeau',
    'This list is incomplete.': 'incomplet',
    'There were several incorrect answers.': 'incorrect/inexact',
    'This is a very inexpensive little car.': 'bon marché',
    'Don’t get dressed up for the party – it will be very informal.': 'décontracté',
    'He wore a denim jacket and jeans.': 'veste/blouson',
    'He wore jeans and a T-shirt.': 'jean',
    'She wore a red jumper with a blue scarf.': 'pull',
    'She put on her make-up.': 'maquillage',
    'Is there enough material for a dress?': 'tissus',
    'He bought the necklace as a present for his wife.': 'collier',
    'She was wearing shorts and sandals.': 'sandales',
    'Kay wore her new scarf.': 'écharpe',
    'She was wearing scruffy jeans.': 'débraillé/négligé',
    'I want to buy a second-hand car.': 'd\'occasion',
    'He wore a blue shirt.': 'chemise',
    'She wore shorts and a T-shirt.': 'short',
    'She wore a dark blue skirt.': 'jupe',
    'I can’t find any socks!': 'chaussette',
    'Her room is very tidy.': 'rangé/ordonné',
    'These shoes are too tight.': 'serré',
    'There’s a hole in these tights.': 'collants',
    'I like your top – is it new?': 'haut',
    'She wore jeans and trainers.': 'baskets',
    'Your trousers are on the chair.': 'pantalon',
    'He wore an unfashionable black suit.': 'démodé',
    'The flowers in our garden are so colourful.': 'coloré',
    'She speaks excellent Spanish.': 'excellent',
    'His office was in an unattractive grey building.': 'peu attrayant',
    'Lewis wore black pants with a yellow T-shirt.': 'pantalon',
    'He was wearing old jeans and a pair of blue sneakers.': 'baskets',
    'She wore a red sweater with a blue scarf.': 'pull',
    'He wore jeans and a leather jacket.': 'cuir'
}

Anglais_voc7_technologie = {
    'They donated $10,000 to the hospital.': 'faire un don',
    'Aluminium cans can be recycled.': 'recycler',
    'Please reuse your envelopes.': 'réutiliser',
    'Students often get a discount on rail travel.': 'réduction',
    'In the sale, everything is half price.': 'soldes',
    'At just £10, the dress was a real bargain!': '(bonne) affaire',
    'Consumers want more information about the food they buy.': 'consommateur',
    'Can I pay by credit card?': 'carte de crédit',
    'He’s borrowed some money but he still has debts.': 'dette',
    'Harrods is a famous department store in London.': 'grand magasin',
    'These jeans were half price in the sale!': 'à moitié prix',
    'Sophie showed me her purchases.': 'achat',
    'Somebody stole my wallet.': 'portefeuille',
    'My Bluetooth headphones are my favourite possession.': 'casque Bluetooth',
    'I’ll take my Bluetooth speaker to the park later.': 'enceinte Bluetooth',
    'I need a new film for my camera.': 'appareil photo/caméra',
    "Put the DVD into the DVD player and press 'play'.": 'lecteur DVD',
    'My e-reader is very convenient.': 'liseuse',
    'The company is selling a new games console.': 'console de jeu',
    'Moira took her laptop to the lecture.': 'ordinateur portable/PC portable',
    'You can use your smartphone to access the internet.': 'smartphone',
    'This game can be played on a tablet or a smartphone.': 'tablette'
}

Anglais_voc8_lieux = {
    'She set the alarm clock for half past six.': 'réveil',
    'I went to the baker’s to buy some bread.': 'boulangerie',
    'She went to the butcher’s for some lamb chops.': 'boucherie',
    'I’m just going to the chemist’s to get my tablets.': 'pharmacie',
    'Katie works in a clothes shop on the High Street.': 'magasin de vêtements',
    'Do up the buttons on your shirt.': 'boutonner/fermer (quelque chose)',
    'Is there a fishmonger’s near here?': 'poissonnerie',
    'We went to the greengrocer’s and bought a lettuce.': 'primeur',
    'Hang your coat up over there.': 'accrocher (quelque chose)',
    'I’m looking for my keys. Have you seen them?': 'chercher (quelque chose)',
    'There is a fruit and vegetable market in the town.': 'marché',
    'I went to the newsagent’s and bought a magazine and a bar of chocolate.': 'marchand de journaux',
    'Harry works at a phone shop in town.': 'magasin de téléphonie',
    'Where’s the main post office?': 'bureau de poste',
    'She put her socks away in the drawer.': 'ranger',
    'Put your coat on.': 'enfiler/mettre',
    'There’s a sandwich shop opposite my office.': 'sandwicherie',
    'I went to the sports shop and bought some new tennis balls.': 'magasin de sport',
    'I took the dress back because it didn’t go with my shoes.': 'rapporter/retourner (quelque chose)',
    'Come in and take your coat off.': 'enlever/retirer (quelque chose)',
    'She opened the drawer and took out a T-shirt.': 'sortir (quelque chose)',
    'I tried the jeans on but they were too small.': 'essayer (quelque chose)',
    'I can’t undo this zip.': 'défaire/déboutonner',
    'She unzipped her bag and took out a key.': 'ouvrir/défaire la fermeture éclair',
    'She zipped up her dress.': 'fermer/remonter la fermeture éclair (de quelque chose)',
    'I went to the bookshop to buy a London guidebook.': 'librairie'
}

Anglais_voc9_corps_sante_menage = {
    'Only the toughest go climbing here in winter.': '(les) plus forts',
    'She fell and broke her ankle.': 'cheville',
    'Put your arms in the air.': 'bras',
    'He lay on his back and looked up at the sky.': 'dos',
    'She held the baby against her chest.': 'poitrine',
    'There are ten competitors in the first race.': 'concurrent',
    'She fell and broke her elbow.': 'coude',
    'Have you washed your face?': 'visage',
    'She cut her finger on some glass.': 'doigt',
    'I keep fit by jogging every day.': 'en forme',
    'I’ve been walking all day and my feet hurt.': 'pied',
    'She held the letter in her hand.': 'main',
    'She turned her head to look at me.': 'tête',
    'I put my hands on my hips.': 'hanche',
    'I fell and cut my knee.': 'genou',
    'She sat down and crossed her legs.': 'jambe',
    'Helen wore a silver chain round her neck.': 'cou',
    'She’s an excellent tennis player.': 'joueur',
    'The French runner is in the lead.': 'coureur',
    'She fell asleep with her head on his shoulder.': 'épaule',
    'One of the skaters fell.': 'skateur/skateuse',
    'There were four 100-metre sprinters in the England team.': 'sprinteur/sprinteuse',
    'Lie on your stomach and lift your arms off the ground.': 'estomac',
    'He’s a good swimmer.': 'nageur/nageuse',
    'Did I tread on your toe? Sorry.': 'orteil',
    'I wear a bracelet on my wrist.': 'poignet',
    'Mark is in bed because he is ill.': 'malade',
    '‘How are you?’ ‘I’m very well, thanks.’': '(aller) bien',
    'I’ve got a headache.': '(avoir un) mal de tête',
    'I’ve got a sore throat.': '(avoir) mal à la gorge',
    'The doctor gave me some antibiotics for my cough.': 'antibiotiques',
    'A nurse put a bandage around my knee.': 'bandage',
    'I was taken to hospital with a broken leg.': 'jambe cassée',
    'I’ve got a burn on my arm.': 'brûlure',
    'I think I’m getting a cold.': 'rhume',
    'I’ve got a bad cough.': 'toux',
    'He had a deep cut on his leg.': 'coupure',
    'The room was hot and I started to feel dizzy.': 'se sentir étourdi/avoir la tête qui tourne',
    'The motion of the boat made her feel sick.': 'avoir la nausée',
    'I think I’ve got flu.': 'grippe',
    'The doctor gave the baby an injection.': 'piqûre',
    'Take this medicine every morning.': 'médicament',
    'She’s on painkillers.': 'antidouleur/analgésique',
    'You should put a plaster on that cut.': 'pansement',
    'Pepper makes you sneeze.': 'éternuer',
    'I’ve got a blocked nose.': 'nez bouché',
    'Lisa has a broken arm.': 'bras cassé',
    'How did you get that bruise on your knee?': 'bleu',
    'Dad washes the car once a week.': '(laver la) voiture',
    'The waiter cleared the table after we finished eating.': 'débarrasser la table',
    'I usually do the ironing on Sunday evenings.': 'repasser/faire le repassage',
    'She does her shopping after work.': 'faire les courses',
    'I’ll do the washing-up if you cook the meal.': 'faire la vaisselle',
    'She felt sick and she had a temperature.': 'avoir de la fièvre',
    'I’ve got hay fever.': 'rhume des foins',
    'My little brother likes to help with the cooking.': 'aider dans la cuisine',
    'I hoovered the floor after the party.': 'passer l\'aspirateur',
    'Please lay the table for eight guests.': 'mettre la table',
    'We loaded the dishwasher after the dinner was over.': 'remplir/vider le lave-vaisselle',
    'I unload the washing machine after the buzzer sounds.': 'remplir/vider la machine à laver',
    'I make my bed every day.': 'faire le lit',
    'What’s the best thing to do when you have a nosebleed?': 'saigner du nez (v)',
    'He came out in a rash where the plant had touched him.': 'rougeur',
    'Could you take out the rubbish, please?': '(sortir la) poubelle',
    'I went to bed feeling cold and shivery.': 'frissonnant',
    'What’s the best treatment for a sprained ankle?': '(avoir une) cheville foulée',
    'I’ve got stomach ache.': '(avoir) mal au ventre',
    'Please tidy your bedroom before your friends arrive.': 'nettoyer sa chambre',
    'I’ve got toothache.': '(avoir un) mal de dent',
    'I feel unwell.': 'souffrant',
    'My brother walks the dog every evening.': 'promener le chien',
    'Shall I hang the washing out?': '(étendre/rentrer le) linge',
    'She felt very weak after her long illness.': 'faible'
}

Anglais_voc10_vie_metiers_voyages = {
    'It’s her birthday today so she’s very happy.': 'heureux',
    'She’s very intolerant of young children.': 'intolérant',
    'It was unfair to give chocolates to my brother and not to me.': 'injuste',
    'Our new neighbours seemed rather unfriendly.': 'antipathique',
    'He was very unhappy when he failed the exam.': 'malheureux',
    'Anyone can enter the competition; age is unimportant.': 'sans importance',
    'It was unkind of you to laugh at her.': 'méchant',
    'They were unlucky to lose because they played very well.': 'malchanceux',
    'It’s dangerous to drive a car at night without any lights.': 'dangereux',
    'My sister is very hard-working.': 'travailleur',
    'Don’t be so lazy – come and help me!': 'paresseux',
    'She was too poor to buy clothes for her children.': 'pauvre',
    'He wants to be rich and famous.': 'riche',
    'Is it safe to swim in this river?': 'sans danger',
    'Breathe deeply and you’ll calm down.': 'respirer à fond',
    'She folded her arms and stared at him.': 'croiser les bras',
    'She’s very shy and never makes eye contact with people.': 'regarder quelqu\'un dans les yeux',
    'She smiled at him and he smiled back.': 'sourire',
    'You’ll look taller if you stand up straight.': 'se tenir droit',
    'Using hand gestures can help you to communicate.': 'faire des gestes',
    'Did you read the article about young fashion designers?': 'article',
    'She has a beautiful voice.': 'beau/joli',
    'He was born in 1990.': 'être né',
    'She died of cancer.': 'mourir',
    'He fell in love with Anna immediately.': 'tomber amoureux (de quelqu\'un)',
    'She got a job as a waitress.': 'trouver un travail',
    'They got divorced last year.': 'divorcer',
    'Kat and Paul got married last year.': 'se marier',
    'I’m hoping to go to university.': 'aller à l\'université',
    'I want to be a doctor when I grow up.': 'grandir',
    'She’s going to have a baby.': 'avoir un bébé',
    'It was a really magical evening.': 'magique',
    'The national flag of Japan is white and red.': 'national',
    'She’s a natural dancer: strong and graceful.': 'naturel',
    'Do you belong to a political party?': 'politique',
    'Richard is a very powerful swimmer.': 'puissant',
    'He is a professional footballer.': 'professionnel',
    'My grandfather retired last year.': 'partir à la retraite',
    'What a wonderful present!': 'merveilleux',
    'Her uncle is a successful actor.': 'accompli',
    'The children all wore traditional costumes.': 'traditionnel',
    'Scientists have made an important new discovery.': 'scientifique',
    'The doctor will see you soon.': 'docteur/médecin',
    'I enjoy reading fiction.': 'fiction',
    'You’ll find biographies in the non-fiction section of the library.': 'non romanesque (adj)',
    '‘David Copperfield’ is a novel by Charles Dickens.': 'roman',
    'My sister works as a nurse in a hospital.': 'infirmière/infirmier',
    'We went to see a play at the National Theatre.': 'pièce',
    'I wrote poems about the countryside.': 'poème',
    'Who wrote the film script?': 'script/texte',
    'He gave me a collection of short stories by Thomas Hardy.': 'nouvelle',
    'After you finish the test, you may take a break.': 'faire une pause',
    'We take a test every Friday in English class.': 'passer un contrôle',
    'Take care when you cross the road.': 'faire attention',
    'The police have now taken control of the situation.': 'prendre le contrôle de/maîtriser (quelque chose)',
    'We all took part in the discussion.': 'participer (à quelque chose)',
    'I took photos of all the famous sights.': 'prendre des photos (de quelque chose)',
    'The wedding of Katherine and Warren will take place on 19 July.': 'avoir lieu',
    'You can’t both use the computer at the same time. Why don’t you take turns?': 'à tour de rôle',
    'Nicky is an accountant.': 'comptable',
    'The builders are starting work on the new school today.': 'ouvrier/ouvrière',
    'John’s an electrician.': 'électricien(ne)',
    'My brother is an engineer.': 'ingénieur(e)',
    'Susan is training to be a lawyer.': 'avocat(e)',
    'The train was full of office workers on their way home.': 'employé(e) de bureau',
    'The plumber came to mend the broken pipes.': 'plombier/plombière',
    'The shop assistant helped me.': 'vendeur/vendeuse',
    'Mary is training to be a vet.': 'vétérinaire',
    'The waiter took our order.': 'serveur/serveuse',
    'Sam wants to be an architect when he grows up.': 'architecte',
    'He works at the car factory.': 'ouvrier/ouvrière d\'usine',
    'My dad is going bald.': 'chauve',
    'He has got a beard.': 'barbe',
    'She is tall and blonde.': 'blond',
    'He’s got curly hair.': 'bouclé',
    'Diane has dyed blonde hair.': 'coloré',
    'He’s got fair hair.': 'clair',
    'She has curly brown hair and freckles.': 'tâches de rousseur',
    'Does she wear glasses?': 'lunettes',
    'John looks like his father.': 'ressembler à (quelqu\'un)',
    'He’s medium-height with dark hair.': 'de taille moyenne',
    'He’s medium-weight with blond hair.': 'de corpulence moyenne',
    'He has got a moustache.': 'moustache',
    'The doctor said I was overweight.': 'en surpoids',
    'Her father was a tall slim man in his forties.': 'mince',
    'He had dark hair and a tanned face.': 'bronzé',
    'He’s tall and thin.': 'mince',
    '‘What’s your new teacher like?’ ‘She’s really nice.’': 'Comment est…?',
    'Climbing Mount Everest was his greatest achievement.': 'accomplissement',
    'Big Ben is a major tourist attraction.': 'attraction',
    'When shall we put up the Christmas decorations?': 'décoration',
    'I get a lot of enjoyment from travelling.': 'plaisir',
    'There isn’t much entertainment for young people in this town.': 'divertissement',
    'We had a big family celebration when Uncle Tony came home.': 'fête',
    'My whole family came to my graduation ceremony.': '(cérémonie de) remise de diplômes',
    'His first reaction was to run away.': 'réaction',
    'Engineers have come up with new ways of saving energy.': 'trouver (une réponse/solution) / trouver le(s) moyen(s) de…',
    'Can you find out what time the train leaves?': 'se renseigner (sur qqch)',
    'I give up – what’s the answer?': 'abandonner',
    'We decided to go ahead with the match in spite of the heavy rain.': 'poursuivre',
    'They put together a list of good hotels nearby.': 'mettre (quelque chose) sur pied/faire (quelque chose)',
    'The company was set up in 1981.': 'fonder (quelque chose)',
    'We worked out the cost of the holiday.': 'résoudre (un problème) / calculer (les coûts)',
    'I am busy cooking now. Can you call back in an hour?': 'rappeler',
    'We were cut off before I could give her my message.': 'couper (quelqu\'un)',
    'I’ll get off the line in case somebody else is trying to call.': 'raccrocher',
    'I tried to call Kate but I couldn’t get through.': 'joindre (quelqu\'un)',
    'I couldn’t hear anyone on the line, so I hung up.': 'raccrocher',
    'Could you hold on a moment, please?': 'attendre',
    'If you don’t understand a word, look it up in a dictionary.': 'chercher',
    'I called her office but nobody picked up.': 'décrocher (le téléphone)',
    'Can you put me through to the manager, please?': 'passer (quelqu\'un) à (quelqu\'un)',
    'Can you speak up? I can’t hear you!': 'parler plus fort',
    'They were very curious about the people who lived upstairs.': 'curieux',
    'You don’t sound very enthusiastic about the idea.': 'enthousiaste',
    'Sarah is a very organized person.': 'organisé',
    'Our waiter was very polite and helpful.': 'poli',
    'Managers must be proactive in preventing problems.': 'proactif',
    'She has been reliable and punctual.': 'ponctuel',
    'He’s a sociable child who’ll talk to anyone.': 'sociable',
    'We lay on the beach in the sun.': 'plage',
    'I stayed in a bed and breakfast.': 'chambre d\'hôtes',
    'We travelled across Europe in a camper van.': 'camping-car',
    'We found a lovely campsite by a lake.': 'terrain de camping',
    'The caravan site was full.': 'caravane',
    'Their holiday house is near the coast.': 'côte',
    'They went on a world cruise.': 'croisière',
    'We went to look at the boats in the harbour.': 'port',
    'I’m going to Spain for my holiday.': 'vacances',
    'We visited the Greek islands last summer.': 'île',
    'We went swimming in the lake.': 'lac',
    'People were fishing along the banks of the river.': 'fleuve',
    'We stayed at a ski resort in the Alps.': 'station de ski',
    'Please remove your shoes before entering the temple.': 'temple',
    'We went to a theme park called Waterland.': 'parc à thème',
    'Did you go up the Eiffel Tower?': 'tour',
    'Is Mount Etna an active volcano?': 'volcan',
    'Come to Niagara and see the spectacular waterfall.': 'chute d\'eau',
    'Their apartment is on the fifth floor.': 'appartement',
    'I’m starting university next fall.': 'automne',
    'Don’t forget to put the garbage out.': 'poubelles',
    'I stayed at a hotel near the airport.': 'hôtel',
    'Is there a movie theater in town?': 'cinéma',
    'Ben plays for the university soccer team.': 'football',
    'They’re on vacation in Hawaii.': 'vacances',
    'They booked a holiday in New York for September.': 'réserver (des vacances)',
    'I had to walk because I missed the bus.': 'manquer/rater (un train)',
    'I packed my bags and called for a taxi.': 'faire (son sac)',
    'She sent me a postcard from California.': 'carte postale',
    'I bought this cowboy hat as a souvenir of Texas.': 'souvenir',
    'Are you going abroad this summer?': 'aller à l\'étranger',
    'We are planning an activity holiday.': 'vacances actives',
    'They have gone away for the weekend.': 'partir',
    'I don’t really like beach holidays; I prefer walking in the countryside.': 'vacances à la mer',
    'We’re planning a camping holiday in France.': 'vacances en camping',
    'We checked into our hotel at 3 p.m.': 's\'enregistrer (à l\'hôtel)',
    'Please check out by 10 a.m.': 'libérer la chambre',
    'I work hard all week so on Sundays I just chill out.': 'se détendre',
    'We didn’t go away on holiday; we just went on day trips.': 'excursion d\'une journée',
    'Can you drop me off here, please?': 'déposer',
    'The children would like to go on a farm holiday.': 'agrotourisme/vacances à la campagne',
    'I’m hoping to get away for a few days in May.': 'partir',
    'When did you get back from your holiday?': 'revenir',
    'I saw the man getting into a blue van.': 'monter dans',
    'Where did you get off the bus?': 'descendre de/du',
    'I got on the train.': 'monter dans',
    'A woman got out of the car.': 'descendre de/du',
    'We went on a guided tour of the castle.': 'visite guidée',
    'I’m looking forward to seeing you again.': 'attendre avec impatience/avoir hâte de',
    'Grandpa picks me up from school every day.': 'aller chercher/passer prendre',
    'People queued up outside the ticket office.': 'faire la queue',
    'We set off for Oxford at two o’clock.': 'partir/se mettre en route',
    'Rose’s parents went on a sightseeing holiday to Prague.': 'séjour touristique',
    'The school organizes a ski trip every winter.': 'vacances au ski',
    'The company offers study holidays for young people in the UK.': 'séjour d\'études',
    'The children go on summer camp in June.': 'colonie de vacances',
    'The plane took off an hour late.': 'décoller',
    'We went on a walking holiday in the Alps.': 'séjour de randonnée',
    'She caught the 10.30 train to Liverpool.': 'prendre/attraper (un train)'
}

Anglais_voc11 = {
    "(avoir) peur (de quelqu'un/quelque chose)": "afraid (of sb / sth)",
    "(être) anxieux/nerveux (à propos de quelqu'un/quelque chose)": "anxious (about sb / sth)",
    "(avoir) honte (de quelqu'un/quelque chose)": "ashamed (of sb / sth)",
    "carte d'anniversaire": "birthday card",
    "ticket de bus": "bus ticket",
    "clés de voiture": "car keys",
    "programme informatique": "computer program",
    "billet/place de concert": "concert ticket",
    "carte de crédit": "credit card",
    "(être) impatient (de)": "excited (about sth)",
    "en avoir marre (de quelque chose/quelqu'un)": "fed up (with sb / sth)",
    "(regarder un) film": "(watch a) film",
    "s'intéresser (à quelqu'un/quelque chose)": "interested (in sb / sth)",
    "être fan/passionné de/apprécier": "keen (on sb / sth)",
    "porte-clés": "key ring",
    "changer (quelque chose)": "make a difference (to sth)",
    "contravention": "parking ticket",
    "fier (de quelqu'un/quelque chose)": "proud (of sb / sth)",
    "sac de courses": "shopping bag",
    "centre commercial": "shopping centre",
    "liste de courses": "shopping list",
    "(faire des) mots croisés": "(do a) crossword",
    "faire de son mieux": "do your best",
    "se coiffer/se faire coiffer (par)": "do your hair",
    "(rendre) service (à quelqu'un)": "(do sb a) favour",
    "(faire) une bonne action": "(do) good",
    "traîner (avec des amis)": "hang out (with friends)",
    "(faire ses) devoirs": "(do) homework",
    "(faire le) ménage": "(do the) housework",
    "(faire un) voyage (n)/voyager (v)": "(make a) journey",
    "choisir": "make a choice",
    "trouver/inventer une excuse": "make an excuse",
    "faire à manger": "make a meal",
    "mettre le bazar/en mettre partout": "make a mess",
    "faire une erreur/se tromper": "make a mistake",
    "(passer un) coup de fil": "(make a) phone call",
    "(faire du) sport": "(do a) sport",
    "partir": "get away",
    "descendre de/du/de la (quelque chose)": "get off (sth)",
    "monter dans (quelque chose)": "get on (sth)",
    "bien s'entendre (avec quelqu'un)": "get on (with sb)",
    "réussir/finir": "get through",
    "arriver à": "get to",
    "apprendre (une langue)": "learn (a language)",
    "se faire des amis": "make friends (with sb)",
    "faire (des gâteaux)": "bake (cakes)",
    "(préparer le) petit-déjeuner": "(make) breakfast",
    "se brosser les dents": "brush your teeth",
    "regarder/consulter (son téléphone)": "check (your phone)",
    "découvrir (de nouveaux groupes)": "check out (new bands)",
    "se peigner": "comb your hair",
    "se préparer (pour quelque chose)": "get ready (for sth)",
    "boire un verre": "have a drink",
    "(fabriquer des) bijoux": "(make) jewellery",
    "(lire un) roman": "(read a) novel",
    "organiser (une fête)": "organize (a party)",
    "(manger un) sandwich": "(have a) sandwich",
    "(utiliser des) réseaux sociaux": "(use) social networking sites",
    "soutenir une équipe": "support a team",
    "prendre le bus": "take the bus",
    "(jouer à des) jeux vidéos": "(play) video games",
    "(pratiquer des) sports nautiques": "(do) water sports",
    "faire un effort": "make an effort",
    "récolter de l'argent": "raise money",
    "s'exprimer": "speak out",
    "participer à": "take part in",
    "assumer/prendre la responsabilité": "take responsibility"
}

Anglais_voc = [
    Anglais_voc1_famille,
    Anglais_voc2_school,
    Anglais_voc3_loisire,
    Anglais_voc4_natur,
    Anglais_voc5_nourriture,
    Anglais_voc6_vetement,
    Anglais_voc7_technologie,
    Anglais_voc8_lieux,
    Anglais_voc9_corps_sante_menage,
    Anglais_voc10_vie_metiers_voyages,
    Anglais_voc11
    ]

